/*
 * WARNING: this is an autogenerated file and will be overwritten by
 * the extension interface script.
 */
#ifndef OPENALEXT_AUTODEFS_H
#define OPENALEXT_AUTODEFS_H

/**
 * string name used to locate this extension
 */
#define S3E_EXT_OPENALEXT_NAME "openalext"
#define S3E_EXT_OPENALEXT_HASH 0x37485935

#endif /* !OPENALEXT_AUTODEFS_H */
